# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Admin/Sync/Portfolio/o_scope/o_scope.srcs/sources_1/bd/o_scope/ip/o_scope_rst_ps7_0_50M_0/o_scope_rst_ps7_0_50M_0.xci
# IP: The module: 'o_scope_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Admin/Sync/Portfolio/o_scope/o_scope.gen/sources_1/bd/o_scope/ip/o_scope_rst_ps7_0_50M_0/o_scope_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'o_scope_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Admin/Sync/Portfolio/o_scope/o_scope.gen/sources_1/bd/o_scope/ip/o_scope_rst_ps7_0_50M_0/o_scope_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'o_scope_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Admin/Sync/Portfolio/o_scope/o_scope.gen/sources_1/bd/o_scope/ip/o_scope_rst_ps7_0_50M_0/o_scope_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'o_scope_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/Admin/Sync/Portfolio/o_scope/o_scope.srcs/sources_1/bd/o_scope/ip/o_scope_rst_ps7_0_50M_0/o_scope_rst_ps7_0_50M_0.xci
# IP: The module: 'o_scope_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Admin/Sync/Portfolio/o_scope/o_scope.gen/sources_1/bd/o_scope/ip/o_scope_rst_ps7_0_50M_0/o_scope_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'o_scope_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Admin/Sync/Portfolio/o_scope/o_scope.gen/sources_1/bd/o_scope/ip/o_scope_rst_ps7_0_50M_0/o_scope_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'o_scope_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Admin/Sync/Portfolio/o_scope/o_scope.gen/sources_1/bd/o_scope/ip/o_scope_rst_ps7_0_50M_0/o_scope_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'o_scope_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
