set_property SRC_FILE_INFO {cfile:C:/Users/Admin/Sync/Portfolio/pj_spectrum_anal/pj_spectrum_anal.srcs/constrs_1/new/pin_configure.xdc rfile:../../../pj_spectrum_anal.srcs/constrs_1/new/pin_configure.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN P18}  [get_ports {cs}]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN N17}  [get_ports {miso}]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN U15}  [get_ports {sclk}]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN M14}  [get_ports {led_err}]
