# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Admin/Sync/Portfolio/pj_spectrum_anal/pj_spectrum_anal.srcs/sources_1/bd/o_scope/ip/o_scope_processing_system7_0_0/o_scope_processing_system7_0_0.xci
# IP: The module: 'o_scope_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Admin/Sync/Portfolio/pj_spectrum_anal/pj_spectrum_anal.gen/sources_1/bd/o_scope/ip/o_scope_processing_system7_0_0/o_scope_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'o_scope_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/Admin/Sync/Portfolio/pj_spectrum_anal/pj_spectrum_anal.srcs/sources_1/bd/o_scope/ip/o_scope_processing_system7_0_0/o_scope_processing_system7_0_0.xci
# IP: The module: 'o_scope_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Admin/Sync/Portfolio/pj_spectrum_anal/pj_spectrum_anal.gen/sources_1/bd/o_scope/ip/o_scope_processing_system7_0_0/o_scope_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'o_scope_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
