# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pin_configure.xdc

# Block Designs: bd/o_scope/o_scope.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==o_scope || ORIG_REF_NAME==o_scope} -quiet] -quiet

# IP: bd/o_scope/ip/o_scope_adc_controller_wrapp_0_0/o_scope_adc_controller_wrapp_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==o_scope_adc_controller_wrapp_0_0 || ORIG_REF_NAME==o_scope_adc_controller_wrapp_0_0} -quiet] -quiet

# IP: bd/o_scope/ip/o_scope_axi_dma_0_0/o_scope_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==o_scope_axi_dma_0_0 || ORIG_REF_NAME==o_scope_axi_dma_0_0} -quiet] -quiet

# IP: bd/o_scope/ip/o_scope_axi_mem_intercon_0/o_scope_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==o_scope_axi_mem_intercon_0 || ORIG_REF_NAME==o_scope_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/o_scope/ip/o_scope_processing_system7_0_0/o_scope_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==o_scope_processing_system7_0_0 || ORIG_REF_NAME==o_scope_processing_system7_0_0} -quiet] -quiet

# IP: bd/o_scope/ip/o_scope_xbar_0/o_scope_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==o_scope_xbar_0 || ORIG_REF_NAME==o_scope_xbar_0} -quiet] -quiet

# IP: bd/o_scope/ip/o_scope_ps7_0_axi_periph_0/o_scope_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==o_scope_ps7_0_axi_periph_0 || ORIG_REF_NAME==o_scope_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/o_scope/ip/o_scope_rst_ps7_0_50M_0/o_scope_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==o_scope_rst_ps7_0_50M_0 || ORIG_REF_NAME==o_scope_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/o_scope/ip/o_scope_auto_pc_0/o_scope_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==o_scope_auto_pc_0 || ORIG_REF_NAME==o_scope_auto_pc_0} -quiet] -quiet

# IP: bd/o_scope/ip/o_scope_auto_us_0/o_scope_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==o_scope_auto_us_0 || ORIG_REF_NAME==o_scope_auto_us_0} -quiet] -quiet

# IP: bd/o_scope/ip/o_scope_auto_pc_1/o_scope_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==o_scope_auto_pc_1 || ORIG_REF_NAME==o_scope_auto_pc_1} -quiet] -quiet

# XDC: c:/Users/Admin/Sync/Portfolio/pj_spectrum_anal/pj_spectrum_anal.gen/sources_1/bd/o_scope/o_scope_ooc.xdc
