# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Admin/Sync/Portfolio/o_scope/o_scope.srcs/sources_1/bd/bd_scope_v4/ip/bd_scope_v4_system_ila_0_0/bd_scope_v4_system_ila_0_0.xci
# IP: The module: 'bd_scope_v4_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/Admin/Sync/Portfolio/o_scope/o_scope.gen/sources_1/bd/bd_scope_v4/ip/bd_scope_v4_system_ila_0_0/bd_0/bd_3601.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3601 || ORIG_REF_NAME==bd_3601} -quiet] -quiet

# IP: c:/Users/Admin/Sync/Portfolio/o_scope/o_scope.gen/sources_1/bd/bd_scope_v4/ip/bd_scope_v4_system_ila_0_0/bd_0/ip/ip_0/bd_3601_ila_lib_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3601_ila_lib_0 || ORIG_REF_NAME==bd_3601_ila_lib_0} -quiet] -quiet

# IP: c:/Users/Admin/Sync/Portfolio/o_scope/o_scope.gen/sources_1/bd/bd_scope_v4/ip/bd_scope_v4_system_ila_0_0/bd_0/ip/ip_1/bd_3601_g_inst_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3601_g_inst_0 || ORIG_REF_NAME==bd_3601_g_inst_0} -quiet] -quiet

# IP: c:/Users/Admin/Sync/Portfolio/o_scope/o_scope.gen/sources_1/bd/bd_scope_v4/ip/bd_scope_v4_system_ila_0_0/bd_0/ip/ip_2/bd_3601_slot_1_aw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3601_slot_1_aw_0 || ORIG_REF_NAME==bd_3601_slot_1_aw_0} -quiet] -quiet

# IP: c:/Users/Admin/Sync/Portfolio/o_scope/o_scope.gen/sources_1/bd/bd_scope_v4/ip/bd_scope_v4_system_ila_0_0/bd_0/ip/ip_3/bd_3601_slot_1_w_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3601_slot_1_w_0 || ORIG_REF_NAME==bd_3601_slot_1_w_0} -quiet] -quiet

# IP: c:/Users/Admin/Sync/Portfolio/o_scope/o_scope.gen/sources_1/bd/bd_scope_v4/ip/bd_scope_v4_system_ila_0_0/bd_0/ip/ip_4/bd_3601_slot_1_b_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3601_slot_1_b_0 || ORIG_REF_NAME==bd_3601_slot_1_b_0} -quiet] -quiet

# IP: c:/Users/Admin/Sync/Portfolio/o_scope/o_scope.gen/sources_1/bd/bd_scope_v4/ip/bd_scope_v4_system_ila_0_0/bd_0/ip/ip_5/bd_3601_slot_1_ar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3601_slot_1_ar_0 || ORIG_REF_NAME==bd_3601_slot_1_ar_0} -quiet] -quiet

# IP: c:/Users/Admin/Sync/Portfolio/o_scope/o_scope.gen/sources_1/bd/bd_scope_v4/ip/bd_scope_v4_system_ila_0_0/bd_0/ip/ip_6/bd_3601_slot_1_r_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3601_slot_1_r_0 || ORIG_REF_NAME==bd_3601_slot_1_r_0} -quiet] -quiet

# IP: c:/Users/Admin/Sync/Portfolio/o_scope/o_scope.gen/sources_1/bd/bd_scope_v4/ip/bd_scope_v4_system_ila_0_0/bd_0/ip/ip_7/bd_3601_slot_2_aw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3601_slot_2_aw_0 || ORIG_REF_NAME==bd_3601_slot_2_aw_0} -quiet] -quiet

# IP: c:/Users/Admin/Sync/Portfolio/o_scope/o_scope.gen/sources_1/bd/bd_scope_v4/ip/bd_scope_v4_system_ila_0_0/bd_0/ip/ip_8/bd_3601_slot_2_w_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3601_slot_2_w_0 || ORIG_REF_NAME==bd_3601_slot_2_w_0} -quiet] -quiet

# IP: c:/Users/Admin/Sync/Portfolio/o_scope/o_scope.gen/sources_1/bd/bd_scope_v4/ip/bd_scope_v4_system_ila_0_0/bd_0/ip/ip_9/bd_3601_slot_2_b_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3601_slot_2_b_0 || ORIG_REF_NAME==bd_3601_slot_2_b_0} -quiet] -quiet

# IP: c:/Users/Admin/Sync/Portfolio/o_scope/o_scope.gen/sources_1/bd/bd_scope_v4/ip/bd_scope_v4_system_ila_0_0/bd_0/ip/ip_10/bd_3601_slot_2_ar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3601_slot_2_ar_0 || ORIG_REF_NAME==bd_3601_slot_2_ar_0} -quiet] -quiet

# IP: c:/Users/Admin/Sync/Portfolio/o_scope/o_scope.gen/sources_1/bd/bd_scope_v4/ip/bd_scope_v4_system_ila_0_0/bd_0/ip/ip_11/bd_3601_slot_2_r_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3601_slot_2_r_0 || ORIG_REF_NAME==bd_3601_slot_2_r_0} -quiet] -quiet

# XDC: c:/Users/Admin/Sync/Portfolio/o_scope/o_scope.gen/sources_1/bd/bd_scope_v4/ip/bd_scope_v4_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_3601_ila_lib_0 || ORIG_REF_NAME==bd_3601_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Admin/Sync/Portfolio/o_scope/o_scope.gen/sources_1/bd/bd_scope_v4/ip/bd_scope_v4_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_3601_ila_lib_0 || ORIG_REF_NAME==bd_3601_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Admin/Sync/Portfolio/o_scope/o_scope.gen/sources_1/bd/bd_scope_v4/ip/bd_scope_v4_system_ila_0_0/bd_0/ip/ip_0/bd_3601_ila_lib_0_ooc.xdc

# XDC: c:/Users/Admin/Sync/Portfolio/o_scope/o_scope.gen/sources_1/bd/bd_scope_v4/ip/bd_scope_v4_system_ila_0_0/bd_0/bd_3601_ooc.xdc

# XDC: c:/Users/Admin/Sync/Portfolio/o_scope/o_scope.gen/sources_1/bd/bd_scope_v4/ip/bd_scope_v4_system_ila_0_0/bd_scope_v4_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_scope_v4_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/Admin/Sync/Portfolio/o_scope/o_scope.srcs/sources_1/bd/bd_scope_v4/ip/bd_scope_v4_system_ila_0_0/bd_scope_v4_system_ila_0_0.xci
# IP: The module: 'bd_scope_v4_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/Admin/Sync/Portfolio/o_scope/o_scope.gen/sources_1/bd/bd_scope_v4/ip/bd_scope_v4_system_ila_0_0/bd_0/bd_3601.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3601 || ORIG_REF_NAME==bd_3601} -quiet] -quiet

# IP: c:/Users/Admin/Sync/Portfolio/o_scope/o_scope.gen/sources_1/bd/bd_scope_v4/ip/bd_scope_v4_system_ila_0_0/bd_0/ip/ip_0/bd_3601_ila_lib_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3601_ila_lib_0 || ORIG_REF_NAME==bd_3601_ila_lib_0} -quiet] -quiet

# IP: c:/Users/Admin/Sync/Portfolio/o_scope/o_scope.gen/sources_1/bd/bd_scope_v4/ip/bd_scope_v4_system_ila_0_0/bd_0/ip/ip_1/bd_3601_g_inst_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3601_g_inst_0 || ORIG_REF_NAME==bd_3601_g_inst_0} -quiet] -quiet

# IP: c:/Users/Admin/Sync/Portfolio/o_scope/o_scope.gen/sources_1/bd/bd_scope_v4/ip/bd_scope_v4_system_ila_0_0/bd_0/ip/ip_2/bd_3601_slot_1_aw_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3601_slot_1_aw_0 || ORIG_REF_NAME==bd_3601_slot_1_aw_0} -quiet] -quiet

# IP: c:/Users/Admin/Sync/Portfolio/o_scope/o_scope.gen/sources_1/bd/bd_scope_v4/ip/bd_scope_v4_system_ila_0_0/bd_0/ip/ip_3/bd_3601_slot_1_w_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3601_slot_1_w_0 || ORIG_REF_NAME==bd_3601_slot_1_w_0} -quiet] -quiet

# IP: c:/Users/Admin/Sync/Portfolio/o_scope/o_scope.gen/sources_1/bd/bd_scope_v4/ip/bd_scope_v4_system_ila_0_0/bd_0/ip/ip_4/bd_3601_slot_1_b_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3601_slot_1_b_0 || ORIG_REF_NAME==bd_3601_slot_1_b_0} -quiet] -quiet

# IP: c:/Users/Admin/Sync/Portfolio/o_scope/o_scope.gen/sources_1/bd/bd_scope_v4/ip/bd_scope_v4_system_ila_0_0/bd_0/ip/ip_5/bd_3601_slot_1_ar_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3601_slot_1_ar_0 || ORIG_REF_NAME==bd_3601_slot_1_ar_0} -quiet] -quiet

# IP: c:/Users/Admin/Sync/Portfolio/o_scope/o_scope.gen/sources_1/bd/bd_scope_v4/ip/bd_scope_v4_system_ila_0_0/bd_0/ip/ip_6/bd_3601_slot_1_r_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3601_slot_1_r_0 || ORIG_REF_NAME==bd_3601_slot_1_r_0} -quiet] -quiet

# IP: c:/Users/Admin/Sync/Portfolio/o_scope/o_scope.gen/sources_1/bd/bd_scope_v4/ip/bd_scope_v4_system_ila_0_0/bd_0/ip/ip_7/bd_3601_slot_2_aw_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3601_slot_2_aw_0 || ORIG_REF_NAME==bd_3601_slot_2_aw_0} -quiet] -quiet

# IP: c:/Users/Admin/Sync/Portfolio/o_scope/o_scope.gen/sources_1/bd/bd_scope_v4/ip/bd_scope_v4_system_ila_0_0/bd_0/ip/ip_8/bd_3601_slot_2_w_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3601_slot_2_w_0 || ORIG_REF_NAME==bd_3601_slot_2_w_0} -quiet] -quiet

# IP: c:/Users/Admin/Sync/Portfolio/o_scope/o_scope.gen/sources_1/bd/bd_scope_v4/ip/bd_scope_v4_system_ila_0_0/bd_0/ip/ip_9/bd_3601_slot_2_b_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3601_slot_2_b_0 || ORIG_REF_NAME==bd_3601_slot_2_b_0} -quiet] -quiet

# IP: c:/Users/Admin/Sync/Portfolio/o_scope/o_scope.gen/sources_1/bd/bd_scope_v4/ip/bd_scope_v4_system_ila_0_0/bd_0/ip/ip_10/bd_3601_slot_2_ar_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3601_slot_2_ar_0 || ORIG_REF_NAME==bd_3601_slot_2_ar_0} -quiet] -quiet

# IP: c:/Users/Admin/Sync/Portfolio/o_scope/o_scope.gen/sources_1/bd/bd_scope_v4/ip/bd_scope_v4_system_ila_0_0/bd_0/ip/ip_11/bd_3601_slot_2_r_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3601_slot_2_r_0 || ORIG_REF_NAME==bd_3601_slot_2_r_0} -quiet] -quiet

# XDC: c:/Users/Admin/Sync/Portfolio/o_scope/o_scope.gen/sources_1/bd/bd_scope_v4/ip/bd_scope_v4_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_3601_ila_lib_0 || ORIG_REF_NAME==bd_3601_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Admin/Sync/Portfolio/o_scope/o_scope.gen/sources_1/bd/bd_scope_v4/ip/bd_scope_v4_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_3601_ila_lib_0 || ORIG_REF_NAME==bd_3601_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Admin/Sync/Portfolio/o_scope/o_scope.gen/sources_1/bd/bd_scope_v4/ip/bd_scope_v4_system_ila_0_0/bd_0/ip/ip_0/bd_3601_ila_lib_0_ooc.xdc

# XDC: c:/Users/Admin/Sync/Portfolio/o_scope/o_scope.gen/sources_1/bd/bd_scope_v4/ip/bd_scope_v4_system_ila_0_0/bd_0/bd_3601_ooc.xdc

# XDC: c:/Users/Admin/Sync/Portfolio/o_scope/o_scope.gen/sources_1/bd/bd_scope_v4/ip/bd_scope_v4_system_ila_0_0/bd_scope_v4_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_scope_v4_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
